name: preco_comb
channels:
  - defaults
dependencies:
  - pandas
  - matplotlib
  - numpy
  - jupyterlab
  - geopy
  - folium
  - streamlit
  - streamlit-folium
  - streamlit>=1.13.0
  - jinja2
  - branca
